package ru.krindra.vknorthtypes.longpoll.bot.events

import kotlinx.serialization.DeserializationStrategy
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.JsonContentPolymorphicSerializer
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive

object EventsSerializer: JsonContentPolymorphicSerializer<ru.krindra.vknorthtypes.longpoll.bot.events.BotLPEvent>(ru.krindra.vknorthtypes.longpoll.bot.events.BotLPEvent::class) {
    private data class SerializerAndType<T>(
        val serializer: KSerializer<T>,
        val type: String
    )
    private val eventsList = listOf(
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageReplyEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageReplyEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageAllowEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageAllowEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageDenyEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageDenyEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageTypingStateEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageTypingStateEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageEventEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageEventEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoCommentNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoCommentNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoCommentEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoCommentEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoCommentRestoreEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.PhotoCommentRestoreEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.AudioNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.AudioNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentRestoreEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentRestoreEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentDeleteEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.VideoCommentDeleteEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.WallPostNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.WallPostNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.WallRepostEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.WallRepostEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyRestoreEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyRestoreEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyDeleteEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.WallReplyDeleteEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.LikeAddEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.LikeAddEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.LikeRemoveEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.LikeRemoveEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostRestoreEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostRestoreEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostDeleteEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.BoardPostDeleteEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentRestoreEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentRestoreEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentDeleteEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketCommentDeleteEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketOrderNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketOrderNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketOrderEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MarketOrderEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupJoinEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupJoinEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupLeaveEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupLeaveEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.UserBlockEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.UserBlockEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.UserUnblockEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.UserUnblockEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.PollVoteNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.PollVoteNewEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupOfficersEditEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupOfficersEditEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupChangeSettingsEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupChangeSettingsEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupChangePhotoEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.GroupChangePhotoEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.VkPayTransactionEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.VkPayTransactionEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.AppPayloadEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.AppPayloadEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionCreateEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionCreateEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionProlongedEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionProlongedEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionExpiredEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionExpiredEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionCancelledEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionCancelledEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionPriceChangedEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutSubscriptionPriceChangedEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutMoneyWithdrawEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutMoneyWithdrawEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutMoneyWithdrawErrorEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.DonutMoneyWithdrawErrorEvent.Companion.type
        ),
        ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.SerializerAndType(
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageNewEvent.serializer(),
            ru.krindra.vknorthtypes.longpoll.bot.events.MessageNewEvent.Companion.type
        )
    )

    override fun selectDeserializer(element: JsonElement): DeserializationStrategy<ru.krindra.vknorthtypes.longpoll.bot.events.BotLPEvent> {
        val type = element.jsonObject["type"]!!.jsonPrimitive.content

        for (e in ru.krindra.vknorthtypes.longpoll.bot.events.EventsSerializer.eventsList) {
            if (type == e.type) return e.serializer
        }
        throw IllegalArgumentException("Unsupported type.\nelement = $element\ntype = $type\n")
    }
}